version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/smartsell"
      JWT_SECRET_KEY: "changeme"
      DAILY_LIMIT: "800"
      NIGHT_START: "22"
      NIGHT_END: "8"
      TIPTOP_PUBLIC_ID: "test"
      TIPTOP_API_SECRET: "test"
    depends_on:
      - db
      - redis
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: smartsell
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  redis:
    image: redis:7
    ports:
      - "6379:6379"