name: Auto Merge Copilot PRs

on:
  pull_request:
    types:
      - labeled

jobs:
  automerge:
    if: github.event.label.name == 'copilot-automerge'
    runs-on: ubuntu-latest
    steps:
      - name: Auto-merge Copilot PR
        uses: pascalgn/automerge-action@v0.16.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
