name: Bot

on:
  issue_comment:
    types: [created]         # реагируем на новые комментарии
  pull_request_review_comment:
    types: [created]
  workflow_dispatch: {}      # можно запустить вручную

permissions:
  contents: write
  pull-requests: write

jobs:
  apply:
    # запускаемся только:
    # - по ручному запуску, ИЛИ
    # - если это комментарий в PR и он содержит "/bot apply"
    if: >
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'issue_comment' &&
       github.event.issue.pull_request != '' &&
       contains(github.event.comment.body, '/bot apply'))
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run bot (apply changes)
        env:
          BOT_COMMENT: ${{ github.event.comment.body }}
        run: |
          python3 .github/bot/apply.py

      - name: Commit & push changes (if any)
        run: |
          set -e
          if git diff --quiet && git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          ISSUE="${{ github.event.issue.number }}"
          [ -z "$ISSUE" ] && ISSUE="${{ github.event.pull_request.number }}"
          [ -z "$ISSUE" ] && ISSUE="manual"
          BRANCH="bot/work/${ISSUE}"
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -B "$BRANCH"
          git add -A
          git commit -m "bot: apply changes for #${ISSUE}"
          git push -f origin "$BRANCH"

      - name: Open or update PR
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          set -e
          ISSUE="${{ github.event.issue.number }}"
          [ -z "$ISSUE" ] && ISSUE="${{ github.event.pull_request.number }}"
          [ -z "$ISSUE" ] && ISSUE="manual"
          BRANCH="bot/work/${ISSUE}"
          BASE="main"
          # если PR уже есть — обновим, иначе создадим
          gh pr list --head "$BRANCH" --state open --json number -q '.[0].number' >/dev/null 2>&1 \
            && gh pr edit "$(gh pr list --head "$BRANCH" --state open --json number -q ".[0].number")" --base "$BASE" --title "Bot changes for #$ISSUE" --body "Automated changes" \
            || gh pr create --base "$BASE" --head "$BRANCH" --title "Bot changes for #$ISSUE" --body "Automated changes"
