name: bot

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

permissions:
  contents: write
  pull-requests: write
  statuses: write
  checks: read

jobs:
  apply:
    if: contains(github.event.comment.body, '/bot apply:')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install bot dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml black ruff

      - name: Run bot (apply changes)
        env:
          GIT_AUTHOR_NAME: smart-bot
          GIT_AUTHOR_EMAIL: bot@users.noreply.github.com
          GIT_COMMITTER_NAME: smart-bot
          GIT_COMMITTER_EMAIL: bot@users.noreply.github.com
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p .github/bot
          python .github/bot/apply.py <<'EOF'
          ${{ github.event.comment.body }}
          EOF

      - name: Format & Lint (best effort)
        run: |
          ruff check . --fix || true
          black . || true

      - name: Create work branch and commit
        run: |
          ISSUE_REF="${{ github.event.issue.number || github.event.pull_request.number || github.run_number }}"
          BRANCH="bot/work/${ISSUE_REF}"
          git checkout -B "$BRANCH"
          git add -A
          git diff --cached --quiet || git commit -m "bot: apply changes for #${ISSUE_REF}"
          git push -f origin "$BRANCH"

      - name: Open or update PR
        run: |
          ISSUE_REF="${{ github.event.issue.number || github.event.pull_request.number || github.run_number }}"
          BRANCH="bot/work/${ISSUE_REF}"
          BASE_BRANCH="${{ github.event.repository.default_branch || 'main' }}"
          # пытаемся создать PR; если уже есть — обновляем его
          gh pr create --base "$BASE_BRANCH" --head "$BRANCH" \
            --title "Bot patch for #${ISSUE_REF}" \
            --body "Automated changes by bot for #${ISSUE_REF}" \
            || gh pr edit $(gh pr list --head "$BRANCH" --json number -q '.[0].number') \
                 --title "Bot patch for #${ISSUE_REF}" \
                 --body "Updated automated changes by bot for #${ISSUE_REF}"
