"""
Alembic autogenerate guards and filters.

This module provides filters for Alembic's autogenerate feature to prevent
destructive operations on DB-only or Core-only objects that don't exist in
the ORM metadata.
"""


def include_object(obj, name, type_, reflected, compare_to):
    """
    Alembic autogenerate guard.

    Filters objects to include in autogenerated migrations:
    - If an object is reflected from the database but has no counterpart in
      ORM metadata (compare_to is None), it is DB-only / Core-only and must
      be ignored to prevent destructive drop_* suggestions.

    Args:
        obj: The SQLAlchemy object (Table, Index, Column, etc.)
        name: The object name
        type_: The object type ('table', 'index', 'column', etc.)
        reflected: True if the object came from reflecting the database
        compare_to: The corresponding ORM metadata object, or None if not found

    Returns:
        bool: False if the object should be excluded, True otherwise.
    """
    # Exclude reflected objects with no ORM counterpart (DB-only objects)
    if reflected and compare_to is None:
        return False
    return True
